package io.github.ciaran11221.compliance.scenario;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Renders docs/SCENARIOS.md from a validated, id-sorted scenario list. A pure function of its
 * input list (no file or clock reads), so the same corpus always renders the same bytes -- that
 * is what lets ScenarioIndexTest compare it against the committed file instead of re-deriving one.
 */
public final class ScenarioIndex {

	private static final String HEADER = "Generated by ScenarioIndexTest. Do not edit by hand -- "
			+ "regenerate with `./mvnw test -Dtest=ScenarioIndexTest -Dscenarios.regenerate=true`.";

	private ScenarioIndex() {
	}

	public static String render(List<Scenario> scenarios) {
		StringBuilder out = new StringBuilder();
		out.append("# Scenario corpus\n\n");
		out.append(HEADER).append("\n\n");

		out.append("## Coverage\n\n");
		Map<String, List<String>> idsByTag = new TreeMap<>();
		for (Scenario scenario : scenarios) {
			for (String tag : scenario.covers()) {
				idsByTag.computeIfAbsent(tag, t -> new ArrayList<>()).add(scenario.id());
			}
		}
		idsByTag.forEach((tag, ids) -> out.append("- `").append(tag).append("`: ").append(String.join(", ", ids)).append("\n"));
		out.append("\n");

		out.append("## Scenarios\n\n");
		out.append("| ID | Title | Kind | Covers | Expected outcome |\n");
		out.append("|---|---|---|---|---|\n");
		for (Scenario scenario : scenarios) {
			out.append("| ").append(scenario.id());
			out.append(" | ").append(scenario.title());
			out.append(" | ").append(scenario.kind());
			out.append(" | ").append(String.join(", ", scenario.covers()));
			out.append(" | ").append(scenario.then().outcome());
			out.append(" |\n");
		}

		return out.toString();
	}

}
