-- Reference data: mutable, current-state tables.

CREATE TABLE staff (
    id                  VARCHAR(64) PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    team                VARCHAR(64) NOT NULL,
    backup_staff_id     VARCHAR(64) NULL REFERENCES staff (id),
    out_of_office_from  TIMESTAMPTZ NULL,
    out_of_office_until TIMESTAMPTZ NULL
);

CREATE TABLE fund (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(32) NOT NULL UNIQUE,
    name         VARCHAR(255) NOT NULL,
    total_assets NUMERIC(19, 4) NOT NULL CHECK (total_assets > 0),
    cash         NUMERIC(19, 4) NOT NULL CHECK (cash >= 0),
    diversified  BOOLEAN NOT NULL
);

CREATE TABLE security (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker                     VARCHAR(32) NOT NULL UNIQUE,
    name                       VARCHAR(255) NOT NULL,
    issuer_name                VARCHAR(255) NOT NULL,
    price                      NUMERIC(19, 4) NOT NULL CHECK (price > 0),
    voting_shares_outstanding  BIGINT NOT NULL CHECK (voting_shares_outstanding > 0),
    avg_daily_volume           BIGINT NOT NULL CHECK (avg_daily_volume > 0)
);

CREATE TABLE holding (
    fund_id     BIGINT NOT NULL REFERENCES fund (id),
    security_id BIGINT NOT NULL REFERENCES security (id),
    quantity    BIGINT NOT NULL CHECK (quantity >= 0),
    PRIMARY KEY (fund_id, security_id)
);

CREATE TABLE restricted_security (
    security_id BIGINT PRIMARY KEY REFERENCES security (id),
    reason      TEXT NOT NULL,
    added_at    TIMESTAMPTZ NOT NULL
);

-- Audit data: insert-only. See V2__audit_insert_only.sql for the triggers that enforce this.

CREATE TABLE trade_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_order_id VARCHAR(128) NOT NULL UNIQUE,
    fund_id         BIGINT NOT NULL REFERENCES fund (id),
    security_id     BIGINT NOT NULL REFERENCES security (id),
    side            VARCHAR(8) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity        BIGINT NOT NULL CHECK (quantity > 0),
    reference_price NUMERIC(19, 4),
    submitted_by    VARCHAR(64) NOT NULL REFERENCES staff (id),
    submitted_at    TIMESTAMPTZ NOT NULL,
    request_hash    VARCHAR(128) NOT NULL
);

CREATE TABLE order_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL REFERENCES trade_order (id),
    event_type   VARCHAR(32) NOT NULL CHECK (event_type IN
                  ('DECIDED', 'QUARANTINED', 'RELEASED', 'REJECTED', 'EXPIRED', 'FILLED', 'CANCELLED')),
    actor        VARCHAR(64) NULL,
    occurred_at  TIMESTAMPTZ NOT NULL,
    detail       JSONB
);

CREATE TABLE decision (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           BIGINT NOT NULL REFERENCES trade_order (id),
    outcome            VARCHAR(8) NOT NULL CHECK (outcome IN ('PASS', 'REVIEW', 'BLOCK')),
    decided_at         TIMESTAMPTZ NOT NULL,
    settings_snapshot  JSONB NOT NULL,
    inputs_snapshot    JSONB NOT NULL
);

CREATE TABLE rule_result (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id    BIGINT NOT NULL REFERENCES decision (id),
    rule_name      VARCHAR(128) NOT NULL,
    outcome        VARCHAR(16) NOT NULL CHECK (outcome IN ('PASS', 'REVIEW', 'BLOCK', 'NOT_APPLICABLE')),
    reason         TEXT,
    measured_value NUMERIC(19, 4) NULL,
    limit_value    NUMERIC(19, 4) NULL
);

CREATE TABLE quarantine (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT NOT NULL UNIQUE REFERENCES trade_order (id),
    reason            VARCHAR(32) NOT NULL CHECK (reason IN
                       ('POSSIBLE_DUPLICATE', 'OPPOSITE_SIDE', 'SENDER_OUT_OF_OFFICE')),
    matched_order_id  BIGINT NULL REFERENCES trade_order (id),
    quarantined_at    TIMESTAMPTZ NOT NULL,
    expires_at        TIMESTAMPTZ NOT NULL,
    assigned_to       VARCHAR(64) NULL REFERENCES staff (id)
);

CREATE TABLE quarantine_resolution (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quarantine_id  BIGINT NOT NULL UNIQUE REFERENCES quarantine (id),
    resolution     VARCHAR(16) NOT NULL CHECK (resolution IN ('RELEASED', 'REJECTED', 'EXPIRED')),
    resolved_by    VARCHAR(64) NULL REFERENCES staff (id),
    resolved_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE limit_change_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key  VARCHAR(64) NOT NULL,
    old_value    NUMERIC(19, 4) NOT NULL,
    new_value    NUMERIC(19, 4) NOT NULL,
    direction    VARCHAR(8) NOT NULL CHECK (direction IN ('TIGHTEN', 'LOOSEN')),
    reason       TEXT NOT NULL,
    requested_by VARCHAR(64) NOT NULL REFERENCES staff (id),
    requested_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE limit_change_preview (
    request_id          BIGINT PRIMARY KEY REFERENCES limit_change_request (id),
    usd_newly_allowed    NUMERIC(19, 4) NULL,
    hides_breach          BOOLEAN NOT NULL,
    required_approvals   INT NOT NULL,
    detail               JSONB
);

CREATE TABLE limit_change_approval (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     BIGINT NOT NULL REFERENCES limit_change_request (id),
    approver       VARCHAR(64) NOT NULL REFERENCES staff (id),
    approver_team  VARCHAR(64) NOT NULL,
    approver_roles VARCHAR(255) NOT NULL,
    approved_at    TIMESTAMPTZ NOT NULL,
    UNIQUE (request_id, approver)
);

CREATE TABLE limit_change_activation (
    request_id   BIGINT PRIMARY KEY REFERENCES limit_change_request (id),
    activates_at TIMESTAMPTZ NOT NULL,
    recorded_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE limit_change_cancellation (
    request_id   BIGINT PRIMARY KEY REFERENCES limit_change_request (id),
    cancelled_by VARCHAR(64) NOT NULL REFERENCES staff (id),
    cancelled_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE setting_value (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key       VARCHAR(64) NOT NULL,
    value             NUMERIC(19, 4) NOT NULL,
    active_from       TIMESTAMPTZ NOT NULL,
    change_request_id BIGINT NULL REFERENCES limit_change_request (id)
);

-- Indexes for lookups the later milestones will do.

CREATE INDEX idx_trade_order_fund_security_submitted ON trade_order (fund_id, security_id, submitted_at);
CREATE INDEX idx_order_event_order_id ON order_event (order_id);
CREATE INDEX idx_setting_value_key_active_from ON setting_value (setting_key, active_from);
