-- A limit-change request that would cross a hard bound in code (a legal maximum, or a value that
-- makes no sense, such as zero) is never created as a limit_change_request: it is refused
-- outright, and the attempt itself is recorded here so a pattern of attempts is visible even
-- though none of them produced a request. Insert-only, like every other audit table.

CREATE TABLE limit_change_refusal (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester        VARCHAR(64) NOT NULL REFERENCES staff (id),
    setting_key      VARCHAR(64) NOT NULL,
    requested_value  NUMERIC(19, 4) NOT NULL,
    reason           TEXT NOT NULL,
    refused_at       TIMESTAMPTZ NOT NULL
);

CREATE TRIGGER trg_limit_change_refusal_no_update_delete
    BEFORE UPDATE OR DELETE ON limit_change_refusal
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_modification();

CREATE TRIGGER trg_limit_change_refusal_no_truncate
    BEFORE TRUNCATE ON limit_change_refusal
    FOR EACH STATEMENT EXECUTE FUNCTION prevent_audit_modification();
